/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2_201700893;

import java.awt.Image;
import javax.swing.ImageIcon;
import static proyecto2_201700893.Inicio.*;
import static proyecto2_201700893.Usuario.*;

/**
 *
 * @author USER
 */
public class VerSobres extends javax.swing.JFrame {

    /**
     * Creates new form VerSobres
     */
    public VerSobres() {
        initComponents();
        cargaInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.setEnabled(false);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel15.setText("Cambiar Sobre");

        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jLabel23.setText("Jugador");

        jLabel18.setText("Equipo");

        jLabel17.setText("Rareza");

        jTextField7.setEditable(false);

        jTextField8.setEditable(false);

        jTextField9.setEditable(false);

        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jButton1.setText("Pegar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel23)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField9)
                            .addComponent(jTextField8)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 63, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        if (!jLabel22.isEnabled()) {
            jLabel22.setEnabled(true);
        }
        if (!jLabel16.isEnabled()) {
            jLabel16.setEnabled(true);
        }
        if (sobre != null) {
            if (sobre.getAnterior() != null) {
                sobre = sobre.anterior;
                numeroEstampa = 1;
                //Pone Primer Jugador
                int estampas[][] = sobre.getSobre().getEstampas();
                String ruta = est.buscarRuta(estampas[numeroEstampa][0]);
                int rareza = est.buscarRareza(estampas[numeroEstampa][0]);
                int codEquipo = est.buscarEquipo(estampas[numeroEstampa][0]);
                int codJugador = est.buscarJugador(estampas[numeroEstampa][0]);
                String nombreJugador = ju.buscarCodJugador(codJugador);
                String nombreEquipo = eq.buscarCodEquipo(codEquipo);
                ImageIcon ImagenJugador = new ImageIcon(getClass().getResource("/" + ruta));
                ImageIcon IconoJugador = new ImageIcon(ImagenJugador.getImage().getScaledInstance(jLabel24.getWidth(), jLabel24.getHeight(), Image.SCALE_DEFAULT));
                jLabel24.setIcon(IconoJugador);
                jTextField7.setText(String.valueOf(rareza));
                jTextField8.setText(nombreEquipo);
                jTextField9.setText(nombreJugador);
                if (eu.buscarPegada(estampas[numeroEstampa][0])) {
                    jButton1.setEnabled(true);
                } else {
                    jButton1.setEnabled(false);
                }
            } else {
                jLabel21.setEnabled(false);
            }
        } else {
            jLabel21.setEnabled(false);
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        if (!jLabel21.isEnabled()) {
            jLabel21.setEnabled(true);
        }
        if (!jLabel16.isEnabled()) {
            jLabel16.setEnabled(true);
        }
        if (sobre != null) {
            if (sobre.getSiguiente() != null) {
                sobre = sobre.siguiente;
                numeroEstampa = 1;
                //Pone Primer Jugador
                int estampas[][] = sobre.getSobre().getEstampas();
                String ruta = est.buscarRuta(estampas[numeroEstampa][0]);
                int rareza = est.buscarRareza(estampas[numeroEstampa][0]);
                int codEquipo = est.buscarEquipo(estampas[numeroEstampa][0]);
                int codJugador = est.buscarJugador(estampas[numeroEstampa][0]);
                String nombreJugador = ju.buscarCodJugador(codJugador);
                String nombreEquipo = eq.buscarCodEquipo(codEquipo);
                ImageIcon ImagenJugador = new ImageIcon(getClass().getResource("/" + ruta));
                ImageIcon IconoJugador = new ImageIcon(ImagenJugador.getImage().getScaledInstance(jLabel24.getWidth(), jLabel24.getHeight(), Image.SCALE_DEFAULT));
                jLabel24.setIcon(IconoJugador);
                jTextField7.setText(String.valueOf(rareza));
                jTextField8.setText(nombreEquipo);
                jTextField9.setText(nombreJugador);
                if (eu.buscarPegada(estampas[numeroEstampa][0])) {
                    jButton1.setEnabled(true);
                } else {
                    jButton1.setEnabled(false);
                }
            } else {
                jLabel22.setEnabled(false);
            }
        } else {
            jLabel22.setEnabled(false);
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        if (numeroEstampa != sobre.getSobre().getCapacidad() - 1) {
            numeroEstampa++;
            int estampas[][] = sobre.getSobre().getEstampas();
            String ruta = est.buscarRuta(estampas[numeroEstampa][0]);
            int rareza = est.buscarRareza(estampas[numeroEstampa][0]);
            int codEquipo = est.buscarEquipo(estampas[numeroEstampa][0]);
            int codJugador = est.buscarJugador(estampas[numeroEstampa][0]);
            String nombreJugador = ju.buscarCodJugador(codJugador);
            String nombreEquipo = eq.buscarCodEquipo(codEquipo);
            ImageIcon ImagenJugador = new ImageIcon(getClass().getResource("/" + ruta));
            ImageIcon IconoJugador = new ImageIcon(ImagenJugador.getImage().getScaledInstance(jLabel24.getWidth(), jLabel24.getHeight(), Image.SCALE_DEFAULT));
            jLabel24.setIcon(IconoJugador);
            jTextField7.setText(String.valueOf(rareza));
            jTextField8.setText(nombreEquipo);
            jTextField9.setText(nombreJugador);
            if (eu.buscarPegada(estampas[numeroEstampa][0])) {
                jButton1.setEnabled(true);
            } else {
                jButton1.setEnabled(false);
            }
        } else {
            jLabel16.setEnabled(false);
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int estampas[][] = sobre.getSobre().getEstampas();
        int codEstampa = estampas[numeroEstampa][0];
        NodoEstampaUsuario nodo = eu.primero;
        do {
            if (nodo.getEstampaUsuario().getCodUsuario() == Integer.parseInt(usuarioActual[0])) {
                if (nodo.getEstampaUsuario().getCodEstampa() == codEstampa) {
                    nodo.getEstampaUsuario().setPegada(1);
                }
            }
            nodo = nodo.siguiente;
        } while (nodo != eu.primero);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cargaInicial() {
        ImageIcon ImagenSiguiente = new ImageIcon(getClass().getResource("next.png"));
        ImageIcon IconoSiguiente = new ImageIcon(ImagenSiguiente.getImage().getScaledInstance(jLabel22.getWidth(), jLabel22.getHeight(), Image.SCALE_DEFAULT));
        ImageIcon ImagenAnterior = new ImageIcon(getClass().getResource("previous.png"));
        ImageIcon IconoAnterior = new ImageIcon(ImagenAnterior.getImage().getScaledInstance(jLabel22.getWidth(), jLabel22.getHeight(), Image.SCALE_DEFAULT));
        jLabel22.setIcon(IconoSiguiente);
        jLabel16.setIcon(IconoSiguiente);
        jLabel21.setIcon(IconoAnterior);
        //Pone Primer Jugador
        int estampas[][] = sobre.getSobre().getEstampas();
        String ruta = est.buscarRuta(estampas[numeroEstampa][0]);
        int rareza = est.buscarRareza(estampas[numeroEstampa][0]);
        int codEquipo = est.buscarEquipo(estampas[numeroEstampa][0]);
        int codJugador = est.buscarJugador(estampas[numeroEstampa][0]);
        String nombreJugador = ju.buscarCodJugador(codJugador);
        String nombreEquipo = eq.buscarCodEquipo(codEquipo);
        ImageIcon ImagenJugador = new ImageIcon(getClass().getResource("/" + ruta));
        ImageIcon IconoJugador = new ImageIcon(ImagenJugador.getImage().getScaledInstance(jLabel24.getWidth(), jLabel24.getHeight(), Image.SCALE_DEFAULT));
        jLabel24.setIcon(IconoJugador);
        jTextField7.setText(String.valueOf(rareza));
        jTextField8.setText(nombreEquipo);
        jTextField9.setText(nombreJugador);
        if (eu.buscarPegada(estampas[numeroEstampa][0])) {
            jButton1.setEnabled(true);
        } else {
            jButton1.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerSobres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VerSobres().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
